<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>NClass.Core</RootNamespace>
    <AssemblyName>NClass.Core</AssemblyName>
    <Nullable>warnings</Nullable>
    <UseImplicitUsings>false</UseImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Translations\Translations.csproj" />
  </ItemGroup>

</Project>
